name: Selenium Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt-get -f install
        google-chrome --version && which google-chrome

    - name: Install Chrome Driver
      run: |
        cd /tmp/
        wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        chromedriver --version

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requeriments.txt

    - name: Run Selenium test
      run: python3 fake_visit.py  # Reemplaza "your_test_file.py" con el nombre de tu archivo de prueba


